apiVersion: v1
kind: Pod
metadata:
  name: test-nad
  namespace: test-net
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name":"vlan200-ovn-localnet"}]'
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
